-- Learning Workshop cloud schema and row-level access rules.
-- Guests stay in localStorage. Only authenticated users may access cloud data.

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  username text not null unique,
  created_at timestamptz not null default now()
);

create table if not exists public.courses (
  id text primary key,
  owner_id uuid not null references auth.users(id) on delete cascade,
  owner_username text not null,
  title text not null,
  category text not null default '',
  levels jsonb not null default '{"easy":[],"medium":[],"hard":[]}'::jsonb,
  created_at timestamptz not null default now()
);

create table if not exists public.progress (
  user_id uuid not null references auth.users(id) on delete cascade,
  course_id text not null references public.courses(id) on delete cascade,
  done_question_ids jsonb not null default '[]'::jsonb,
  level_score jsonb not null default '{}'::jsonb,
  level_done jsonb not null default '{}'::jsonb,
  last_accessed bigint,
  primary key (user_id, course_id)
);

create table if not exists public.stats (
  user_id uuid primary key references auth.users(id) on delete cascade,
  total_correct integer not null default 0 check (total_correct >= 0),
  total_answered integer not null default 0 check (total_answered >= 0)
);

create table if not exists public.checkins (
  user_id uuid primary key references auth.users(id) on delete cascade,
  last_date date,
  streak integer not null default 0 check (streak >= 0),
  total_days integer not null default 0 check (total_days >= 0),
  history jsonb not null default '[]'::jsonb
);

create table if not exists public.achievements (
  user_id uuid not null references auth.users(id) on delete cascade,
  achievement_id text not null,
  title text not null,
  description text not null default '',
  icon text not null default '',
  unlocked_at bigint not null,
  primary key (user_id, achievement_id)
);

create table if not exists public.mistakes (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  course_id text not null references public.courses(id) on delete cascade,
  course_title text not null,
  level text not null check (level in ('easy', 'medium', 'hard')),
  question_id text not null,
  question jsonb not null,
  user_answer_text text not null default '',
  wrong_count integer not null default 1 check (wrong_count > 0),
  mastered boolean not null default false,
  updated_at timestamptz not null default now(),
  unique (user_id, course_id, question_id)
);

alter table public.profiles enable row level security;
alter table public.courses enable row level security;
alter table public.progress enable row level security;
alter table public.stats enable row level security;
alter table public.checkins enable row level security;
alter table public.achievements enable row level security;
alter table public.mistakes enable row level security;

revoke all on public.profiles, public.courses, public.progress, public.stats,
  public.checkins, public.achievements, public.mistakes from anon;
grant select, insert, update, delete on public.profiles, public.courses,
  public.progress, public.stats, public.checkins, public.achievements,
  public.mistakes to authenticated;
grant usage, select on all sequences in schema public to authenticated;

drop policy if exists "profiles_self_select" on public.profiles;
drop policy if exists "profiles_self_insert" on public.profiles;
drop policy if exists "profiles_self_update" on public.profiles;
create policy "profiles_self_select" on public.profiles for select to authenticated using (id = auth.uid());
create policy "profiles_self_insert" on public.profiles for insert to authenticated with check (id = auth.uid());
create policy "profiles_self_update" on public.profiles for update to authenticated using (id = auth.uid()) with check (id = auth.uid());

drop policy if exists "courses_authenticated_read" on public.courses;
drop policy if exists "courses_owner_insert" on public.courses;
drop policy if exists "courses_owner_update" on public.courses;
drop policy if exists "courses_owner_delete" on public.courses;
create policy "courses_authenticated_read" on public.courses for select to authenticated using (true);
create policy "courses_owner_insert" on public.courses for insert to authenticated with check (owner_id = auth.uid());
create policy "courses_owner_update" on public.courses for update to authenticated using (owner_id = auth.uid()) with check (owner_id = auth.uid());
create policy "courses_owner_delete" on public.courses for delete to authenticated using (owner_id = auth.uid());

drop policy if exists "progress_self" on public.progress;
create policy "progress_self" on public.progress for all to authenticated using (user_id = auth.uid()) with check (user_id = auth.uid());
drop policy if exists "stats_self" on public.stats;
create policy "stats_self" on public.stats for all to authenticated using (user_id = auth.uid()) with check (user_id = auth.uid());
drop policy if exists "checkins_self" on public.checkins;
create policy "checkins_self" on public.checkins for all to authenticated using (user_id = auth.uid()) with check (user_id = auth.uid());
drop policy if exists "achievements_self" on public.achievements;
create policy "achievements_self" on public.achievements for all to authenticated using (user_id = auth.uid()) with check (user_id = auth.uid());
drop policy if exists "mistakes_self" on public.mistakes;
create policy "mistakes_self" on public.mistakes for all to authenticated using (user_id = auth.uid()) with check (user_id = auth.uid());
